MAP_TARGET_SCALE = 2048     # expected size of the map
DESCRITIZE_SCALE = 5        # scale of the map
DESCRITIZE_THRESHOLD = 90  # threshold for the map
ARUCO_SIZE_CM    = 4.4      # size of the aruco marker (cm)
ROBOT_RADIUS_CM  = 10.28    # radius of the robot (cm)
SHUTTER_SPEED    = 0.01      # time between two frames (s)
KP_LINEAR        = 10        # proportional gain for linear speed
KI_LINEAR        = 0.25     # integral gain for linear speed
KD_LINEAR        = 2.5      # derivative gain for linear speed
KP_ANGULAR       = 100      # proportional gain for angular speed
KI_ANGULAR       = 0.15     # integral gain for angular speed
KD_ANGULAR       = 5        # derivative gain for angular speed
ANGULAR_SPEED_CORRECTION = 0.5 # correction factor for angular speed
THRESHOLD_DISTANCE_TO_TARGET_CM = 2 # threshold distance to target (cm)
MOTOR_SPEED_ERROR = 0.1     # relative error on the motor speed
# ROTATION_MULTIPLIER = 1.0   # multiplier for the rotation speed
MOTOR_SPEED_TO_CM = 0.03    # conversion factor from motor speed to cm/s
AVOIDING_PERIOD   = 2.0     # seconds to avoid an obstacle
OBSTACLE_DETECTION_MAX = 5000 # maximum value for obstacle detection
START_AVOIDANCE_DIST = 2000 # threshold for starting obstacle avoidance
STOP_AVOIDANCE_DIST = 4000  # threshold for stopping obstacle avoidance
REMOVE_SMALL_OBSTACLES_IN_CM2 = 50 # threshold for removing small obstacles
MAX_ROBOT_SPEED = 150       # maximum speed of the robot
VISUALIZATION_REFRESH_TIME = 0.1 # time between two visualization updates
TARGET_CHANGE_THRESHOLD = 10 # threshold for changing the target